//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zadolzhnost
    {
        public int ID_zadolzhnost { get; set; }
        public decimal Summa { get; set; }
        public int SrokOplati { get; set; }
        public int ID_FIO { get; set; }
    
        public virtual FIO FIO { get; set; }
    }
}
